### PR TITLE
rely on the core mongo helper

### PR DESCRIPTION
**Pull request by Thovi98**

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
Bookworm will not work with mongo < 7.0 but mongo has to be updated one major version at the time. So I suggest updating it incrementally until the Bookworm release of Yunohost.

**Comment by gcollin** [comment]
Thanks, I didn't know you could just use the global helper like that !

**Comment by Thovi98** [comment]
Yes, since Yunohost version 11.2.12 🥳

**Pull request merged**
